server:
  port: ${PORT:5000}

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:h2:./hexlet
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

# BEGIN
  springdoc:
    swagger: #    swagger-ui:
      path: /swagger.html
      # /path #http://localhost:5000/swagger-ui.html
      # swagger-ui custom path
      #springdoc.swagger-ui.path=/swagger-ui.html